###
GET https://google.com

###
GET http://localhost:3000/about

###
GET http://localhost:3000/ap1/v1/users

###
GET http://localhost:3000/ap1/v1/users/1

###
DELETE http://localhost:3000/ap1/v1/users/1

###
POST http://localhost:3000/ap1/v1/users
Content-Type: application/json

{
    "firstName": "Moshe",
    "lastName": "Goldberg",
    "age": 30,
    "email": "goldberg@newpaltz.edu",
    "password": "123456"
}